# Generated by Django 3.2.6 on 2021-08-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210814_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=255, unique=True, verbose_name='Email:'),
        ),
    ]
