# Generated by Django 3.2.6 on 2021-08-16 10:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Product name:')),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'), django.core.validators.MaxValueValidator(Decimal('100')))])),
                ('fats', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'), django.core.validators.MaxValueValidator(Decimal('100')))])),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'), django.core.validators.MaxValueValidator(Decimal('100')))])),
                ('calories', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
