# Generated by Django 3.2.6 on 2021-08-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Product name:')),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=2)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=2)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
